permalink: /:categories/:title.html
url: "http://gamejam.witharms.com/"
full_name: "Your Full Name"
first_name: "First Name"
last_name: "Last Name"
blog_title: "GameJam "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "gamejam"
copyright_year: "2016"
google_analytics_code: ""
# aboutme: "Something about the author here"
# twitter: "Ghosteyes1"
# github: "pasindud"
# facebook: "mepasindu"
# linkined_url: ""
